name: space_ru
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  google_fonts: ^6.2.1
  formz: ^0.6.0
  user_repository:
    path: packages/user_repository

dev_dependencies:
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0


flutter_icons:
  ios: true
  android: "launcher_icon"
  image_path_ios: "lib/assets/launcher/launch.png"
  image_path_android: "lib/assets/launcher/launch.png"

flutter:
  uses-material-design: true


  assets:
    - lib/assets/google.png
    - lib/assets/launch.png
